version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  spring-app:
    image: veventumt/authforstock
    ports:
      - "8080:8080"
    depends_on:
      - postgres