spring:
  application:
    name: AuthForStockApplication
  datasource:
    url: jdbc:h2:mem:security-security
    driverClassName: org.postgresql.Driver
    username:
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: fbvkcmlxsdoncxzklsdfsddfsdfsdvsdc