spring:
  application:
    name: AuthForStockApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: fbvkcmlxsdoncxzklsdfsddfsdfsdvsdc