spring:
  application:
    name: AuthForStockApplication
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    driverClassName: org.postgresql.Driver
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: HldPJxTjwhAVfklMnZeLjqWzyXrpviDuNUCRtaYIBQoGSOgsKcFmbE